const PDFDocument = require('pdfkit');

const generatePrescriptionPDF = (patient, doctorName) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.rect(0, 0, doc.page.width, 80).fill('#2563EB');
    doc.fillColor('white')
      .fontSize(22)
      .font('Helvetica-Bold')
      .text('Smart Clinic AI', 50, 25);
    doc.fontSize(10)
      .font('Helvetica')
      .text('AI-Powered Healthcare Management', 50, 52);

    doc.moveDown(3);

    // Prescription title
    doc.fillColor('#1e293b')
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('PRESCRIPTION', { align: 'center' });

    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#e2e8f0').stroke();
    doc.moveDown(1);

    // Patient details
    doc.fontSize(11)
      .font('Helvetica-Bold')
      .fillColor('#374151')
      .text('PATIENT DETAILS', 50);
    doc.moveDown(0.5);

    const detailsY = doc.y;
    doc.font('Helvetica').fontSize(10).fillColor('#6b7280');
    doc.text(`Name:`, 50, detailsY);
    doc.fillColor('#1e293b').text(patient.name, 130, detailsY);

    doc.fillColor('#6b7280').text(`Age:`, 50, detailsY + 20);
    doc.fillColor('#1e293b').text(`${patient.age} years`, 130, detailsY + 20);

    doc.fillColor('#6b7280').text(`Gender:`, 50, detailsY + 40);
    doc.fillColor('#1e293b').text(patient.gender, 130, detailsY + 40);

    doc.fillColor('#6b7280').text(`Phone:`, 50, detailsY + 60);
    doc.fillColor('#1e293b').text(patient.phone, 130, detailsY + 60);

    doc.fillColor('#6b7280').text(`Date:`, 50, detailsY + 80);
    doc.fillColor('#1e293b').text(patient.date, 130, detailsY + 80);

    doc.fillColor('#6b7280').text(`Token:`, 50, detailsY + 100);
    doc.fillColor('#1e293b').text(`#${patient.tokenNumber}`, 130, detailsY + 100);

    doc.fillColor('#6b7280').text(`Doctor:`, 300, detailsY);
    doc.fillColor('#1e293b').text(doctorName || 'N/A', 370, detailsY);

    doc.moveDown(6);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#e2e8f0').stroke();
    doc.moveDown(1);

    // Symptoms
    doc.fontSize(11)
      .font('Helvetica-Bold')
      .fillColor('#374151')
      .text('REPORTED SYMPTOMS');
    doc.moveDown(0.5);
    doc.fontSize(10)
      .font('Helvetica')
      .fillColor('#1e293b')
      .text(patient.symptoms || 'N/A', { width: 500 });

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#e2e8f0').stroke();
    doc.moveDown(1);

    // Diagnosis
    doc.fontSize(11)
      .font('Helvetica-Bold')
      .fillColor('#374151')
      .text('DIAGNOSIS & CONSULTATION NOTES');
    doc.moveDown(0.5);
    doc.fontSize(10)
      .font('Helvetica')
      .fillColor('#1e293b')
      .text(patient.consultationNotes || 'N/A', { width: 500 });

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#e2e8f0').stroke();
    doc.moveDown(1);

    // Prescription
    doc.fontSize(11)
      .font('Helvetica-Bold')
      .fillColor('#374151')
      .text('PRESCRIPTION');
    doc.moveDown(0.5);
    doc.fontSize(10)
      .font('Helvetica')
      .fillColor('#1e293b')
      .text(patient.prescription || 'N/A', { width: 500 });

    doc.moveDown(2);

    // Footer
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#e2e8f0').stroke();
    doc.moveDown(1);
    doc.fontSize(9)
      .fillColor('#9ca3af')
      .text('This prescription was generated by Smart Clinic AI.', { align: 'center' })
      .text('Please follow your doctor\'s instructions carefully.', { align: 'center' });

    doc.end();
  });
};

module.exports = { generatePrescriptionPDF };